services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminPassword
      POSTGRES_DB: travelswipe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secretpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - activities-api
      - cities-api
      - countries-api
    restart: unless-stopped
    profiles: ["app", "ng"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:80
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:80
      - HOSTNAME=0.0.0.0
    profiles: ["FE", "app"]
  activities-api:
    build:
      context: ./dotNetBe
      dockerfile: Activities.Api/Dockerfile
    container_name: activities-api
    ports:
      - "5101:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MongoDb: mongodb://admin:secretpassword@mongodb:27017/travelswipe_activities?authSource=admin
      ConnectionStrings__PostgreSQL: "Host=postgres;Port=5432;Database=travelswipe_activities;Username=postgres;Password=adminPassword"
      ConnectionStrings__Redis: "redis:6379"
      SerpApi__ApiKey: db7d54b17ebc694a81e668e447da8fabcc58b55fcd050de740b066bdaead540c
      SerpApi__BaseUrl: https://serpapi.com/
      Foursquare__BaseUrl: https://api.foursquare.com/v3/
      Foursquare__ApiKey: 1ODAJME4YSDNOXFWXCPI2RGC3DNXMZX1PUGMY3YTURZ0D4K5
      Nominatim__BaseUrl: https://nominatim.openstreetmap.org/
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: admin
      RabbitMQ__Password: secretpassword
    depends_on:
      mongodb:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    profiles: ["app", "activities", "microservices"]

  cities-api:
    build:
      context: ./dotNetBe
      dockerfile: Cities.Api/Dockerfile
    container_name: cities-api
    ports:
      - "5102:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSQL: "Host=postgres;Port=5432;Database=travelswipe_cities;Username=postgres;Password=adminPassword"
      ConnectionStrings__Redis: "redis:6379"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: admin
      RabbitMQ__Password: secretpassword
    depends_on:
      mongodb:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    profiles: ["app", "cities", "microservices"]

  countries-api:
    build:
      context: ./dotNetBe
      dockerfile: Countries.Api/Dockerfile
    container_name: countries-api
    ports:
      - "5103:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSQL: "Host=postgres;Port=5432;Database=travelswipe_countries;Username=postgres;Password=adminPassword"
      ConnectionStrings__Redis: "redis:6379"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: admin
      RabbitMQ__Password: secretpassword

    depends_on:
      mongodb:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    profiles: ["app", "countries", "microservices"]

volumes:
  mongo_data:
    external: true
    name: travelswipe_mongo_data # the original volume name
  postgres_data:
  redis_data:
  rabbitmq_data:
